title: "Kentang Mustofa Jakarta - Mulya Cuisine"
email: feedback@kentangmustofa.biz.id
description: "Pusat oleh-oleh Kentang Mustofa Jakarta resep asli Mulya Cuisine. Renyah, tanpa pengawet, dan halal. Keuntungan untuk pendidikan inklusif."
baseurl: ""
url: "https://kentangmustofa.biz.id"

# Owner Data (Update Instagram & Maps disini)
owner:
  name: "Mulyati Sholeha"
  whatsapp: "6285882611413"
  instagram: "mulyacuisine.id"
  address: "Jl. Haji Nawi No. 39A, Larangan Selatan, Kota Tangerang, Banten 15154"
  maps_link: "https://maps.app.goo.gl/tH7XJgq8zP6zJ8d7A" # Link pencarian lokasi

# Build Settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
